apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: srlinux
  name: srlinux
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srlinux
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: srlinux
    spec:
      serviceAccount: sr-sa
      serviceAccountName: sr-sa
      containers:
      - command:
        - sudo
        - bash
        - /opt/srlinux/bin/sr_linux
        image: ghcr.io/nokia/srlinux
        name: srlinux
        securityContext:
          privileged: true
          runAsUser: 1001
          runAsGroup: 1001
        volumeMounts:
        - mountPath: /tmp
          name: topology
      volumes:
      - name: topology
        configMap:
          name: syed-sr-router-config
          items:
            - key: topology.yml
              path: topology.yml
