apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: srlinux1
  name: srlinux1
spec:
  containers:
  - args:
    - sudo
    - bash
    - /opt/srlinux/bin/sr_linux
    image: ghcr.io/nokia/srlinux
    name: srlinux1
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /tmp/topology.yml
      name: topology
  volumes:
  - name: topology
    hostPath:
      path: ./topology.yml
      type: File
  restartPolicy: Always

