apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: srlinux-single
  name: srlinux-single
spec:
  containers:
  - args:
    - sudo
    - bash
    - /opt/srlinux/bin/sr_linux
    image: ghcr.io/nokia/srlinux
    name: srlinux-single
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /tmp/topology.yml
      name: topology
  volumes:
  volumes:
  - name: topology
    configMap:
      name: syed-sr-router-config
      items:
        - key: topology.yml
          path: topology.yml

