apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: srlinux
  name: srlinux
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: srlinux
  type: NodePort
status:
  loadBalancer: {}
